version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "5.2.x"
    schedule:
      interval: daily
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "5.1.x"
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
