SELECT setval('public.funcionalidade_id_seq', 42, true);
SELECT setval('public.geres_id_seq', 12, true);
SELECT setval('public.unidade_id_seq', 90, true);
SELECT setval('public.macroregional_id_seq', 4, true);
SELECT setval('public.municipio_id_seq', 298, true);
SELECT setval('public.perfil_funcionalidade_id_seq', 3470, true);
SELECT setval('public.perfil_id_seq', 34, true);
SELECT setval('public.usuario_unidade_id_seq', 42, true);
SELECT setval('public.usuario_id_seq', 179, true);